Launch v1 (#66)
* Add autogenerated client into launch v1 (#63)

* add autogenerated client into launch v1

* flake8 conf

* pylint and mypy too

* isort

* Squashed commit of the following:

commit 9533e471160320bd29db0db31556cb429f50f31f
Author: phil-scale <phil.chen@scale.com>
Date:   Mon Dec 19 23:12:49 2022 -0800

    update deps

commit 14d1f118370c4a911cfcf2f4be40e8037269e93c
Author: phil-scale <phil.chen@scale.com>
Date:   Mon Dec 19 23:07:38 2022 -0800

    fix pylint check

commit f6c159de6e853c20c9ad8a21c244bc66bf590ecb
Author: phil-scale <phil.chen@scale.com>
Date:   Mon Dec 19 23:05:20 2022 -0800

    fix

commit 26825f6a079a477f7cc6218233167184d0984d63
Author: phil-scale <phil.chen@scale.com>
Date:   Mon Dec 19 22:58:44 2022 -0800

    fix tests

commit f2c0db858dbcf8b2df674c44a8363d09139c3933
Merge: 443cb0c 7bdf37b
Author: phil-scale <phil.chen@scale.com>
Date:   Mon Dec 19 14:33:23 2022 -0800

    Merge remote-tracking branch 'origin/master' into phil/launch-v1

commit 443cb0c9f2ee34051d16a23e77ab73a782e4b241
Author: Phil Chen <phil.chen@scale.com>
Date:   Wed Dec 14 21:58:33 2022 -0800

    fix

commit 7dee94fae83563ad7e4cac9f6b3c3de690eb98ab
Author: Phil Chen <phil.chen@scale.com>
Date:   Wed Dec 14 18:27:13 2022 -0800

    fixes

commit 44efbf437f615b0a7e90b8db132908b47d8ef086
Author: Phil Chen <phil.chen@scale.com>
Date:   Fri Dec 2 12:13:55 2022 -0800

    fix

commit 7b74884512418b6a487a8f5f567eb674a7ec98a7
Author: Phil Chen <phil.chen@scale.com>
Date:   Fri Dec 2 11:03:45 2022 -0800

    fix

commit 451de716fd903fbbaf3e0061fc9560444f640f94
Author: Phil Chen <phil.chen@scale.com>
Date:   Fri Dec 2 01:05:26 2022 -0800

    basic auth and fixes

commit 607332eef52d6d047383313a9a09a0b0bfae060d
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:47:43 2022 -0800

    update reqs

commit ce11dfffe14bfb64b759f81ab03b2e5adbae1d35
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:40:10 2022 -0800

    black

commit ae4e040a8a9b045784dff7bd4293cf4848c075fa
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:38:29 2022 -0800

    fix mypy

commit 58c62ce9ffc80876685a5090f43f17f52a4d35f3
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:34:14 2022 -0800

    change to deployment_state

commit a582155037780306b94b60e75cbbb7828f63bc77
Merge: ff24539 aa0c0b2
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:29:16 2022 -0800

    Merge branch 'launch-v1' into phil/launch-v1

commit aa0c0b29f014c9ba54ebc364e06725c917548cc8
Author: Phil Chen <92065453+phil-scale@users.noreply.github.com>
Date:   Thu Dec 1 14:28:48 2022 -0800

    Add autogenerated client into launch v1 (#63)

    * add autogenerated client into launch v1

    * flake8 conf

    * pylint and mypy too

    * isort

commit ff2453936aa9ba6f2f5ac4aa2744b039def27f6b
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 14:28:15 2022 -0800

    address comment

commit a53c23de28b8a9163f24cd45a3ce0dc3cab690cf
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 09:25:55 2022 -0800

    black

commit b5d4787cf4448b161e53899308b88ee7dd83a303
Author: Phil Chen <phil.chen@scale.com>
Date:   Thu Dec 1 09:14:52 2022 -0800

    launch v1 client updates

* fixes

* Use new autogenerated python client for v1 (#67)

* Phil/upload schemas (#68)

* update client

* try again

* fix import

* fixes

* wip

* fixes

* try fix again

* fix

* fixes

* add pydantic schema support

* add test

* fix

* fix flat schemas

* black and isort

* Launch v1 client updates for batch jobs and callbacks (#69)

* add autogen client

* update client to use new API for callbacks and batch jobs

* fix

* Update clone-bundle route (#70)

* Update clone bundle function

* Revert unnecessary change

* pr comments

* mypy

* black

* ✨ Updated v1 CLI ✨  (#71)

* updated v1 python client

* specify encoding

* use utf-8

* add ID to list endpoints and get endpoint

* Use spinner while loading in cli and edit endpoints from CLI (#72)

* clone_bundle_with_changes server route expects new_app_config, not app_config

* update reqs

* use base64 and json to encode batch job payloads (#74)

* fix base64 encoding

* Add CLI command for getting batch job status (#75)

* Use timedelta for printing batch job duration

* fix sync endpoint request

* fix sync endpoint result on error

* Add timeouts to `EndpointResponseFuture` (#77)

* Send requests to launch endpoint (#76)

Adding `send` command, ie: `launch tasks send`

* print more info in launch CLI

* Clean up unused code and use ruff instead of flake8 (#79)

* use ruff instead of flake8

* update lint cfgs

* fix typing

* rm pipeline test

* Add features to `launch endpoints list` (#80)

* add orderby, descending and num_gpus

* reverting changes

* typing_extensions for py37

* remove double print (#82)

* filter bundles and endpoints by name in CLI (#84)

* New documentation site (#81)

* Use mkdocs and write docs for launch

* updates

* add site_url

* add overview of concepts

* fix

* some more fixes

* Update CLI help string to 118 instead of 78 chars wide

* test python code in docs and docstrings

* update team tags to infra

* update literal to typing_extensions

* add some reqs

* fix

* add sleep to callbacks

* updates

* update deps

* address comments

* fix pylint

* Callback custom auth (#85)

* update clients

* Update client to support custom callback auth

* update docs

* update docs with mtls default example

* add copy extension

* Add endpoint to client

* Update docs and external client for priority API change (#87)

* new docs

* format

* format isort

* new changes

* new formatted changes

* formatting

* updated client

* changing from str to bool

* removing site

* making sure?

* update to v1

* Update autogen client with v2 bundles (#88)

* Update autogenerated python client

* fix tests

* Model bundles v2 python API (#89)

* Add model bundles v2 API

* add get list and clone routes too

* use types and make docstrings more informative

* fixes

* fix status

* Documentation for model bundles v2 (#90)

* Add documentation for model bundles

* address comments

* fix

* launch v2 bundles API (#91)

* v2 bundles api copy

* Formated with black

* isort and fix 2 mypy errors

launch/connection.py:14: error: Incompatible default for argument "endpoint" (default has type "None", argument has type "str")  [assignment]
launch/client.py:1811: error: Incompatible default for argument "urls" (default has type "None", argument has type "List[str]")  [assignment]

* Fix package import

* Added readiness_initial_delay_seconds

* updating docs

* Added create TritonEnhancedRunnableImageFlavor bundle

* fix

* fix

* fix

* rm space

* update docs

* fix index docs to new apis

---------

Co-authored-by: Phil Chen <phil.chen@scale.com>

* update mkdocs readme

* use logging lib

---------

Co-authored-by: Yi Xu <yi.xu@scale.com>
Co-authored-by: Adrian Lam <72415932+adlam-scale@users.noreply.github.com>
Co-authored-by: Anirudh Jain <88404749+Anirudh-Scale@users.noreply.github.com>
Co-authored-by: Malcolm Greaves <malcolmgreaves@users.noreply.github.com>